### PR TITLE
Create page about GDG Logo Generators

### PR DESCRIPTION
**Pull request by tasomaniac**
Info about Logo generators are added. I guess this needs to be added to table of contents as well, right? Sorry I am new here :)

### CODE REVIEW

**Comment by friedger** [comment]
There is already a link at https://gdg-wisdom.gitbooks.io/gdg-wisdom-2016/content/what_is_a_gdg/promoting.html

**Comment by friedger** [comment]
Would you like to move all from promoting to projects?

**Comment by tasomaniac** [comment]
My initial goal was to promote the open source project by @abdonrd 

Then I included the official logo generator too. I think it also makes sense for them to be in Promoting page. 

This page is more for developers. 

Can we have both pages at the same time?

**Comment by abdonrd** [comment]
Thank you @tasomaniac! :smile:

**Comment by friedger** [comment]
@tasomaniac Ok. Could you add a line at 

https://github.com/gdg-wisdom/wisdom-2016/blob/master/projects/README.md

and

https://github.com/gdg-wisdom/wisdom-2016/blob/master/SUMMARY.md

**Comment by tasomaniac** [comment]
@friedger I will add the necessary items there. But feel free not to merge this and suggest changes. Duplication is not good either.

**Comment by friedger** [comment]
the project folder is the best place I think. The description from promotion should be shortened and a link to the logo generator page should be added there.

So, once items added, I am happy to merge.

**Comment by tasomaniac** [comment]
Comments are addressed.

**Comment by friedger** [comment]
Thank you for the contribution

**Pull request merged**
